---
name: lint

on:
  push:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Lint dotfiles
        run: |
          ## Needed until [[https://github.com/koalaman/shellcheck/issues/2199][#2199]] gets merged.
          ln -sv ./setup/conf/shellcheckrc .shellcheckrc
          ./setup/lint.docker
